### ISSUE TITLE
Does launch

### ISSUE THREAD

**Issue by trololol42** [kli512/bombparty-assist#1]
Yo I may be a little dumb but what and how I do have to open the "script" and in what order, cause I did launch everything, search.py and chromedriver.exe looks to work fine, but jklm_bombparty don't do anything and insertwords.js give me an error 
"Scipt :
C:\Users\sacbo\OneDrive\Bureau\bombparty-assist-main
Ligne : 9
Caract : 56 
Erreur: Erreur de syntaxe
code: 800A03EA
Source: Erreur de compilation MicrosoftJscript"

Also can you add a version for french version of bombparty ? (I have a WordList if needed)

**Comment by kli512** [comment]
Hi, I updated the readme with more specific directions. Could you try following those and see if it helps?

I will add support for other dictionaries soon - if you want to provide a word list for the french dictionary that would be great.

**Comment by trololol42** [comment]
Thank you for the little tutorial, I didn't know how to install the selenium package, here is a dictionary.txt with french words that I found [words.txt](https://github.com/kli512/bombparty-assist/files/6511233/words.txt)

There is also this one from an old bombparty cheat https://raw.githubusercontent.com/necrosis159/bombparty/master/fr-FR.json

**Comment by kli512** [comment]
If you're using windows 10 64 bit, I'll put out a release with a precompiled exe for it soon - I probably can't help much if you're not on windows 10 or some linux distro. 

I will work on adding the french dictionary as well. Thanks for the dictionary.
